### ISSUE TITLE
Support buildpacks distributed via GitHub

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#776] opened 2020-08-05 14:26 UTC
### Description
As a pack user, it would be ideal to be able to use a buildpack that is hosted on GitHub.

For example:

```
pack build tmp-cnb-image \
    --builder "gcr.io/paketo-buildpacks/builder:base" \
    --buildpack from=builder
    --buildpack "https://github.com/buildpacks/samples/tree/main/buildpacks/hello-world" 
```

OR

```
pack build sample-image \
    --builder gcr.io/paketo-buildpacks/builder:base-platform-api-0.3 \
    --buildpack from=builder \
    --buildpack https://github.com/ciberkleid/buildpack-samples-hello-world/archive/master.zip
```

### Proposed solution

Do a more robust lookup for `buildpack.toml`. If the `buildpack.toml` isn't found in the top-level directory, look one level deeper.

### Alternatives considered

1. Support `--strip` similar to `tar`
    - Providing this option to the user doesn't seem viable since it wouldn't be possible to specify which BP to apply this option to. We wouldn't want to apply it to all of them due to the potential of mixed content.
1. Support `subdir` for buildpacks that aren't at the top-level
    - > There is no good syntax for this.
1. Support `git` protocol for download
    - This would be nice but doesn't solve for local downloaded zipped/tared contents.

### Additional context
- [x] This feature should be documented somewhere

- Relevant [slack conversation](https://buildpacks.slack.com/archives/C94UJCNV6/p1596568375390100)

**Comment by jromero** [comment] 2020-08-05 14:38
Updated to provide the simplest solution that enables this feature.

**Comment by natalieparellano** [comment] 2023-08-18 19:52
Closing as duplicate of https://github.com/buildpacks/pack/issues/776

**Closed by natalieparellano** 2023-08-18 19:52 UTC
Labels: type/enhancement, size/md, status/ready

**Comment by loewenstein** [comment] 2023-08-18 20:02
> Closing as duplicate of #776

@natalieparellanothis is self-referential, by accident I suppose.

**Comment by natalieparellano** [comment] 2023-08-18 20:12
@loewenstein thank you! I meant https://github.com/buildpacks/pack/issues/1865
