### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by trisberg** [buildpacks/pack#111] opened 2019-03-15 15:55 UTC
Error messages are often a bit cryptic, would be helpful to provide more hints of what went wrong.

error during export when not authenticated to docker:
  `Error: failed to : unsupported status code 401; body:`

error during analyze when wrong password provided for docker user:
  `Error: connect to repo store 'docker.io/trisberg/hello': <empty transport.Error response>`

**Comment by mikesprague** [comment] 2019-04-04 13:43
I was unable to test out the new beta and getting the following error until I re-logged into Docker via CLI:

```
Using default builder image cloudfoundry/cnb:cflinuxfs3
Pulling builder image cloudfoundry/cnb:cflinuxfs3 (use --no-pull flag to skip this step)
ERROR: connect to repo store 'cloudfoundry/cnb:cflinuxfs3': <empty transport.Error response>
```

Would have saved a lot of time and frustration to know that my Docker credentials had expired locally.

Also wondering why we need to be logged in to pull public containers 🤷‍♂️ Seems like an unnecessary requirement.

**Comment by Zanadar** [comment] 2019-12-18 17:02
@ameyer-pivotal You've been owning logging/errors. What do you think? Can we close this issue?

**Comment by ameyer-pivotal** [comment] 2019-12-18 17:31
@Zanadar Yeah we can close this. The issue is stale, but the effort is an ongoing thing to be more helpful when we write error messages.

**Closed by ameyer-pivotal** 2019-12-18 17:31 UTC

**Comment by jromero** [comment] 2019-12-18 19:06
Relates to https://github.com/buildpacks/docs/issues/96

**Comment by jromero** [comment] 2019-12-18 19:09
Maybe this issue was over generalized when it reality there _could_ be something we can do to provide some guidance. The problem with this error is that it's not easy to determine what the issue is as you could see in https://github.com/buildpacks/docs/issues/96.
