### ISSUE TITLE
Prefixed Mixin resolution too strict

### ISSUE THREAD

**Issue by cborealis** [buildpacks/pack#1134] opened 2021-04-16 13:05 UTC
### Summary
When a stack provides a mixin for both build and run images, like 'tar', and a buildpack declares that it needs tar, but only for build, like 'build:tar', the build fails.

Essentially, requiring 'build:tar' forbids tar being available in the run image, which does not make sense.

### Reproduction
create a buildpack with the following configuration:

```
[[stacks]]
id = "io.buildpacks.stacks.bionic"
mixins = ["build:tar"]

```

##### Current behavior
the build fails, even though tar is available in the build image, with the error
`requires missing mixin(s): build:tar`

##### Expected behavior
the build succeeds

---

##### pack info
Pack:
  Version:  0.0.0+git-acbd243 (newest version built from source)
  OS/Arch:  linux/amd64

Default Lifecycle Version:  0.10.2

Supported Platform APIs:  0.3, 0.4

Config:
  default-builder-image = "[REDACTED]"

##### docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 50.11GiB
 Name: docker-desktop

**Comment by natalieparellano** [comment] 2021-04-16 13:53
I want to say that this is a duplicate of https://github.com/buildpacks/pack/issues/868.

This is targeted for the next platform API (0.7).

**Comment by jromero** [comment] 2021-04-19 17:55
Yes, that sounds like exactly the same issue. @cborealis please re-open or comment if that's not true. Closing this issue as a duplicate.

**Closed by jromero** 2021-04-19 17:55 UTC
Labels: status/triage, type/bug
