### ISSUE TITLE
Cache failure when building sample aspnet app

### ISSUE THREAD

**Issue by Extant-1** [buildpacks/pack#973] opened 2020-12-01 22:07 UTC
### Summary

When building the aspnet app from the sample code using the steps in the tutorial, an error occurs:

```
Setting default process type 'web'
ERROR: failed to export: saving image: failed to commit cache: backing up cache: rename c:\launch-cache\committed c:\launch-cache\committed-backup: The system cannot find the path specified.
ERROR: failed to build: executing lifecycle: failed with status code: 502
```

Building with --no-cache does not fix the issue.

##### Steps
1. git clone https://github.com/buildpacks/samples
2. cd samples/apps/aspnet
3. pack build sample-app --path . --builder cnbs/sample-builder:dotnet-framework-1809 --trust-builder

##### Current behavior
A cache error occurred in the exporting step

Log output: https://gist.github.com/Extant-1/947f08c96f37c8e0dd89ca6a05327203

##### Expected behavior
The build to succeed

##### pack info
```
Pack:
  Version:  0.0.0+git-79adc30.build-1660
  OS/Arch:  windows/amd64

Default Lifecycle Version:  0.9.3

Supported Platform APIs:  0.3, 0.4

Config:
(no config file found at C:\Users\***\.pack\config.toml)
```

##### docker info
```
Client:
 Debug Mode: false
 Plugins:
  scan: Docker Scan (Docker Inc., v0.3.4)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 12
 Server Version: 19.03.13
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows 10 Enterprise Version 1809 (OS Build 17763.1577)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.83GiB
 Name: ENETT-NB338
 ID: SPMT:245S:GBYM:C2TZ:WYYY:MH66:HBMA:SBOQ:6EOV:IM27:DAFE:JEHX
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by micahyoung** [comment] 2020-12-02 18:11
Thanks @Extant-1 for submitting the issue and repro details. My understanding of the error message is that one of the cache volumes that is supposed to be bind-mounted inside the `build` container isn't present or readable during export.

I haven't run into this particularly error before and I haven't been able to reproduce this on a similar (though not equivalent) environment - `Windows 10 Enterprise LTSC 2019 Version 1809 (OS Build 17763.1339)` and your same version of Docker Desktop.

I'm wondering the issue might be outside the particular `pack` <-> Docker combination... and maybe some small difference between 1809 `SAC` vs `LTSC` or something specific to your environment, as we've seen some buggy volume-permissions behavior with Docker in the past. If you could, please run this docker-only command on the same environment and comment with your output:

```powershell
docker run --rm --interactive --user ContainerAdministrator -v launchcachetest:c:/launch-cache mcr.microsoft.com/windows/nanoserver:1809 cmd /c "echo > c:\launch-cache\test.txt && dir /q /s /p c:\launch-cache"
```

**Comment by Extant-1** [comment] 2020-12-02 22:06
Hi @micahyoung, output from the docker command:

```
Unable to find image 'mcr.microsoft.com/windows/nanoserver@sha256:6fb87453ff19b5ff1e98377042aab75979a29c171718756e095b41a5fbae4840' locally
sha256:6fb87453ff19b5ff1e98377042aab75979a29c171718756e095b41a5fbae4840: Pulling from windows/nanoserver
f1b217fe8837: Pull complete
Digest: sha256:6fb87453ff19b5ff1e98377042aab75979a29c171718756e095b41a5fbae4840
Status: Downloaded newer image for mcr.microsoft.com/windows/nanoserver@sha256:6fb87453ff19b5ff1e98377042aab75979a29c171718756e095b41a5fbae4840
 Volume in drive C has no label.
 Volume Serial Number is 44F6-1F34

 Directory of c:\launch-cache

12/03/2020  08:56 AM    <DIR>          ...                    .
12/03/2020  08:56 AM    <DIR>          ...                    ..
12/03/2020  08:56 AM                13 ...                    test.txt
               1 File(s)             13 bytes

     Total Files Listed:
               1 File(s)             13 bytes
               2 Dir(s)  453,445,566,464 bytes free
```

**Comment by micahyoung** [comment] 2020-12-03 10:23
Strange. Volume mounts are working as expected through the `docker` CLI...  What's the result with the nanoserver builder?

1. git clone https://github.com/buildpacks/samples (or re-use the one you have)
1. cd samples/apps/aspnet
1. pack build sample-app --path . --builder _cnbs/sample-builder:nanoserver-1809_ --trust-builder

**Comment by Extant-1** [comment] 2020-12-03 22:16
@micahyoung , same error using the nanoserver builder:

```
nanoserver-1809: Pulling from cnbs/sample-builder
Digest: sha256:09b653a9e73bb4fe3e1ff2e31d439e15464f4c1a00c56fe50ee6e3dbc517ff9e
Status: Image is up to date for cnbs/sample-builder:nanoserver-1809
nanoserver-1809: Pulling from cnbs/sample-stack-run
Digest: sha256:5529a917d32293e949f9501ffc14d56664f20d7fdfee873df88504fb5f716adc
Status: Image is up to date for cnbs/sample-stack-run:nanoserver-1809
[36m===> DETECTING[0m
samples/hello-world-windows 0.0.1
[36m===> ANALYZING[0m
[36m===> RESTORING[0m
[36m===> BUILDING[0m
--- Hello World buildpack
     env_dir: c:\platform\env
     env_vars:
       CNB_STACK_ID=io.buildpacks.samples.stacks.nanoserver-1809
       COMSPEC=C:\Windows\system32\cmd.exe
       env_dir=c:\platform\env
       layers_dir=c:\layers\samples_hello-world-windows
       PATH=c:\Windows\system32;C:\Windows
       CNB_BUILDPACK_DIR=c:\cnb\buildpacks\samples_hello-world-windows\0.0.1
       PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.JS;.WS;.MSC
       plan_path=C:\Windows\TEMP\plan.218919394\samples_hello-world-windows\plan.toml
       PROMPT=$P$G
       SYSTEMROOT=C:\Windows
     layers_dir: c:\layers\samples_hello-world-windows
     plan_path: C:\Windows\TEMP\plan.218919394\samples_hello-world-windows\plan.toml
     plan contents:
       [[entries]]
       name = "some-world"
--- Done
[36m===> EXPORTING[0m
Adding 1/1 app layer(s)
Reusing layer 'launcher'
Reusing layer 'config'
Adding label 'io.buildpacks.lifecycle.metadata'
Adding label 'io.buildpacks.build.metadata'
Adding label 'io.buildpacks.project.metadata'
[33;1mWarning: [0mdefault process type 'web' not present in list []
[31;1mERROR: [0mfailed to export: saving image: failed to commit cache: backing up cache: rename c:\launch-cache\committed c:\launch-cache\committed-backup: The system cannot find the path specified.

```

**Comment by micahyoung** [comment] 2020-12-04 15:52
Hmmm. To try rule out any serious issues, I went ahead and tested all this out on a pristine Windows 10 Enterprise 1809 17763.1577 virtual machine (azure image: `MicrosoftWindowsDesktop:Windows-10:rs5-enterprise-g2:17763.1577.2011031610`) using a local non-admin user... and never saw anything odd. 

Is there any significantly different from my setup and your machine? Is you machine domain joined or otherwise have significant non-default security constraints?

**Comment by jromero** [comment] 2021-03-05 16:54
Hi @Extant-1, just following up on this. Did you ever figure out what may be happening here?

**Comment by briandealwis** [comment] 2021-05-12 14:16
GCP Buildpacks received an [error report about this issue](https://github.com/GoogleCloudPlatform/buildpacks/issues/135).  The problem is in `Cache.CreateCache()`, specifically this line:

https://github.com/buildpacks/pack/blob/88c345552c7bfb90ebd3a622e5a16ffdb29e72bd/internal/registry/registry_cache.go#L190

The cache is created in `$TMPDIR` and then moved into the cache root.  But the rename will fail if `$TMPDIR` is on a different file system.

**Comment by natalieparellano** [comment] 2023-08-18 19:54
Fixed in https://github.com/buildpacks/lifecycle/pull/856

**Closed by natalieparellano** 2023-08-18 19:54 UTC
Labels: type/bug, status/incomplete
