### ISSUE TITLE
Cache is not working with 0.7 (and probably earlier) API

### ISSUE THREAD

**Issue by leshik** [buildpacks/pack#1373] opened 2022-02-16 04:29 UTC
### Summary

The cache is not working as described in the [documentation](https://buildpacks.io/docs/buildpack-author-guide/create-buildpack/caching/) with the latest API. The first build completes fine, and a subsequent one lacks a layer that was supposed to be cached, rendering the resulting image unworkable.

### Reproduction

Either follow the [documentation](https://buildpacks.io/docs/buildpack-author-guide/create-buildpack/caching/) or use the `ruby` sample from [here](https://github.com/buildpacks/samples), updating it for `0.7` compatibility beforehand, below is my diff:

```diff
diff --git a/buildpacks/ruby-bundler/bin/build b/buildpacks/ruby-bundler/bin/build
index a87e63b..0d9715a 100755
--- a/buildpacks/ruby-bundler/bin/build
+++ b/buildpacks/ruby-bundler/bin/build
@@ -12,7 +12,7 @@ ruby_layer_dir="${layers_dir}/ruby"
 mkdir -p "${ruby_layer_dir}"

 # determine ruby version provided during detection
-ruby_version=$(cat "${plan_path}" | yj -t | jq -r '.entries[] | select(.name == "ruby") | .version')
+ruby_version=$(cat "${plan_path}" | yj -t | jq -r '.entries[] | select(.name == "ruby") | .metadata.version')

 echo "---> Downloading and extracting Ruby ${ruby_version}"
 ruby_url=https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-18/ruby-${ruby_version}.tgz
@@ -20,8 +20,11 @@ wget -q -O - "${ruby_url}" | tar -xzf - -C "${ruby_layer_dir}"

 # 3. MAKE RUBY AVAILABLE DURING LAUNCH
 cat > "${ruby_layer_dir}.toml" <<EOL
+[types]
 launch = true
-metadata = "${ruby_version}"
+
+[metadata]
+version = "${ruby_version}"
 EOL

 # 4. MAKE RUBY AVAILABLE TO THIS SCRIPT
@@ -37,7 +40,7 @@ gem install bundler --no-ri --no-rdoc
 # Compares previous Gemfile.lock checksum to the current Gemfile.lock
 bundler_layer_dir="${layers_dir}/bundler"
 local_bundler_checksum=$(sha256sum Gemfile.lock | cut -d ' ' -f 1)
-remote_bundler_checksum=$(cat "${bundler_layer_dir}.toml" | yj -t | jq -r .metadata 2>/dev/null || echo 'not found')
+remote_bundler_checksum=$(cat "${bundler_layer_dir}.toml" | yj -t | jq -r .metadata.checksum 2>/dev/null || echo 'not found')

 if [[ -f Gemfile.lock && ${local_bundler_checksum} == ${remote_bundler_checksum} ]] ; then
   # Determine if no gem dependencies have changed, so it can reuse existing gems without running bundle install
@@ -47,11 +50,14 @@ if [[ -f Gemfile.lock && ${local_bundler_checksum} == ${remote_bundler_checksum}
 else
   # Determine if there has been a gem dependency change and install new gems to the bundler layer; re-using existing and un-changed gems
   echo "---> Installing gems"
-  mkdir "${bundler_layer_dir}"
+  mkdir -p "${bundler_layer_dir}"
   cat > "${bundler_layer_dir}.toml" <<EOL
+[types]
 cache = true
 launch = true
-metadata = "${local_bundler_checksum}"
+
+[metadata]
+checksum = "${local_bundler_checksum}"
 EOL
   bundle install --path "${bundler_layer_dir}" --binstubs "${bundler_layer_dir}/bin"
 fi
diff --git a/buildpacks/ruby-bundler/bin/detect b/buildpacks/ruby-bundler/bin/detect
index aae4936..c9f94a7 100755
--- a/buildpacks/ruby-bundler/bin/detect
+++ b/buildpacks/ruby-bundler/bin/detect
@@ -31,5 +31,7 @@ name = "ruby"
 #
 [[requires]]
 name = "ruby"
+
+[requires.metadata]
 version = "${version}"
 EOL
\ No newline at end of file
diff --git a/buildpacks/ruby-bundler/buildpack.toml b/buildpacks/ruby-bundler/buildpack.toml
index d7f1e4f..84099fc 100644
--- a/buildpacks/ruby-bundler/buildpack.toml
+++ b/buildpacks/ruby-bundler/buildpack.toml
@@ -1,5 +1,5 @@
 # Buildpack API version
-api = "0.2"
+api = "0.7"

 # Buildpack ID and metadata
 [buildpack]
```

Then run:

```
pack build sample-ruby-bundler-app --path ./apps/ruby-bundler --buildpack ./buildpacks/ruby-bundler --builder cnbs/sample-builder:bionic --trust-builder -v
```

##### Current behavior

The resulting image lacks a layer that was supposed to be cached (bundler in the example), rendering it unworkable.

##### Expected behavior

Cached layers should be present in the resulting image as was the case with API `0.2`.

##### pack info

```
Pack:
  Version:  0.24.0+git-79a40b7.build-3148
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.13.3

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6, 0.7, 0.8

Config:
```

##### docker info

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.16.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 14
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.843GiB
 Name: docker-desktop
 ID: QBKB:VCX4:OSHQ:XPAJ:363Q:6VJR:DE7U:D7LG:A6RW:4WVD:TWDZ:5BX3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by jromero** [comment] 2022-02-16 14:51
@leshik thank you for reporting this. It seems as though this would be a lower-level issue and not so much `pack`. Let me see if I can get other people's eyes on this.

@buildpacks/buildpack-authors-tooling-maintainers any idea what may be going on here? Is there a better place for this issue?

**Comment by leshik** [comment] 2022-02-18 09:24
@jromero likely it's a bug in the restore functionality of [buildpacks/lifecycle](https://github.com/buildpacks/lifecycle), do you want me to open this issue there?

**Comment by leshik** [comment] 2022-02-18 10:03
@samj1912 I don't get it. What should be changed in this particular sample buildpack then? It sets `cache = true` under `[types]` already.

**Comment by samj1912** [comment] 2022-02-18 10:07
Yes - but it needs to do that each time regardless of whether it found an existing cache or not. Currently it only does that conditionally when it doesn't find a cache.

The `cache=true` key signals that the layer should be re-used next time or not and it is wiped from the types table during each re-build. Currently this would mean that the cache would be preserved across 1 rebuild, but not more than 1 rebuild. 

FWIW, this is also what our current buildpack authors tutorial does and it is a bug in our buildpacks author tutorial since the instructions were not updated in accordance with the migration guide. The API however is functioning as intended.

**Comment by natalieparellano** [comment] 2022-10-12 20:33
Closing as this seems resolved, feel free to reopen if I'm mistaken.

**Closed by natalieparellano** 2022-10-12 20:33 UTC
Labels: type/bug, status/resolved
