### ISSUE TITLE
Use fully qualified image names (podman compatibility)

### ISSUE THREAD

**Issue by FlorianLudwig** [buildpacks/pack#1218] opened 2021-06-29 15:36 UTC
### Description

For podman compatibility (and more) it would be good to use fully qualified image names ( = include registry in image name)

Example: Instead of:

```
buildpacksio/lifecycle:0.11.3
```

use:
```
docker.io/buildpacksio/lifecycle:0.11.3
```

### Changes

- [ ] Update internal references to images to include registry
- [ ] Update docs to use fully qualified image names in examples

### Additional context

See also:
 - https://www.redhat.com/en/blog/be-careful-when-pulling-images-short-name
 - https://github.com/buildpacks/pack/issues/966#issuecomment-870689430

**Comment by matejvasek** [comment] 2021-06-29 15:47
Not only `podman` compatibility, it should be also safer.

**Comment by jromero** [comment] 2021-06-29 19:21
I like this suggestion although I know there will be some necessary discussion about ease-of-use considering that there's a large number of users that are coming from the docker CLI where the host is assumed if missing.

**Comment by FlorianLudwig** [comment] 2021-06-30 13:40
@jromero 

changing:

https://github.com/buildpacks/pack/blob/88c345552c7bfb90ebd3a622e5a16ffdb29e72bd/internal/config/config.go#L130

would not be visible end-user facing. So at least for that part, no ease-of-use consideration would be necessary?

Updating the docs so that all examples include the host might be different.

I do not want to suggest to enforce only accepting image names that contain the host.

**Comment by jromero** [comment] 2021-08-10 14:03
@FlorianLudwig I would say that we are on the same page.

1. We should update the reference to lifecycle image
2. Update the docs to include host (I am curious how this would affect image names for images that are only intended to live on the docker daemon. I'm assuming you would still set the host to `docker.io` which might be contentious).
3. We should NOT enforce only accepting image names that contain a host.

**Comment by hhiroshell** [comment] 2024-03-25 12:43
I'm thinking about giving it a try. 
But what's the meaning of the `contribfest` label? Is there anything that should be considered when working on this issue?

**Comment by natalieparellano** [comment] 2024-03-26 15:49
@hhiroshell it would be great to get your help on this! Re the label, we flagged this issue for a Contribfest session that we hosted at KubeCon EU, but the issue is still up for grabs.

**Comment by hhiroshell** [comment] 2024-03-27 07:39
Thanks @natalieparellano, so could you please assign this to me?

**Comment by hhiroshell** [comment] 2024-05-01 09:09
Now, I'm working on fixing documentation at https://github.com/buildpacks/docs/pull/702.

**Comment by hhiroshell** [comment] 2024-05-31 08:17
To the reviewers,

The document is now ready for review. I apologize for the relatively large pull request, as the entire document has been revised.

**Comment by hhiroshell** [comment] 2024-06-10 07:33
Completed for works no the codes.
- https://github.com/buildpacks/pack/pull/2185

**Closed** 2024-11-13 18:04 UTC
Labels: type/enhancement, help wanted, good first issue, status/ready
