### ISSUE TITLE
Improve performance when creating a dynamic builder

### ISSUE THREAD

**Issue by ipmb** [buildpacks/pack#1582] opened 2023-01-03 19:06 UTC
### Description

When running `pack build` with a buildpack that is not in the builder, I see a significant delay before the `DETECTING` phase begins.

### Proposed solution

@natalieparellano suggested there may be some room for optimization here:

> maybe instead of creating an ephemeral image we could add the provided buildpacks as volume mounts… or something. It may be worth opening an issue

### Additional context
- [ ] This feature should be documented somewhere

[Discussion from CNCF's Slack](https://cloud-native.slack.com/archives/C0331B61A1Y/p1671551763499679)

Here is an example where it takes 1.5 minutes. I'm starting the process from the Go API, but it would be equivalent to `pack build -b heroku/nodejs,heroku/python -B heroku/buildpacks:20 myimage`:

![CleanShot 2022-12-19 at 20 58 54@2x](https://user-images.githubusercontent.com/319156/210423554-e82b836f-0e87-450b-8720-ed384e1aa894.png)

**Comment by dmikusa** [comment] 2023-01-03 21:32
Yes, I've hit this as well. For me, it has happened when I've tried to use large buildpacks with `pack build -b foo -b bar ...` and the Paketo builders.

The classic us case that triggers it is when you have a buildpack that bundles dependencies within the buildpack image. What is normally a 10M image turns in to possibly hundreds of MB or even a GB, depending on how many binaries you bundle into the image. When you start to add in hundreds of MBs, the process gets painfully slow.

I suspect you could recreate this by just packaging a buildpack & including a single large file (say 500MB) into that buildpack. Then try to run `pack build -b big-bp...`.

I've hit this mostly on Mac (x86_64 & ARM64), but that's my daily driver. I've hit it with Docker Desktop and a stand-alone custom Docker VM. I think it's worse on ARM64, but can't objectively prove that.

Hope that helps! Happy to help test any potential changes.

**Comment by ipmb** [comment] 2023-01-03 23:10
I don't think it's the case that these buildpacks are particularly large. Here's what I'm seeing from `heroku/python` (which afaik pulls from the URL below):

```
$ curl -sLo python.tar https://cnb-shim.herokuapp.com/v1/heroku/python
$ ls -lh python.tar
-rw-rw-r-- 1 pete pete 1.8M Jan  3 15:55 python.tar
```

...and the Node buildpacks:

```
$ docker inspect public.ecr.aws/heroku-buildpacks/heroku-nodejs-buildpack:0.5.12 | jq '.[0].Size' | numfmt --to=iec
12M
$ docker inspect public.ecr.aws/heroku-buildpacks/heroku-nodejs-engine-buildpack:0.8.13 | jq '.[0].Size' | numfmt --to=iec
5.0M
$ docker inspect public.ecr.aws/heroku-buildpacks/heroku-nodejs-npm-buildpack:0.5.2 | jq '.[0].Size' | numfmt --to=iec
32K
```

**Comment by ipmb** [comment] 2023-01-04 23:16
> What is your build scenario? Local/CI? What OS? What Docker version?

CI (AWS Codebuild), Alpine Linux, Docker version 20.10.22, build 3a2c30b

**Comment by ipmb** [comment] 2023-02-02 19:39
I've tried switching from `-b heroku/nodejs,heroku/python` to `-b urn:cnb:builder:heroku/nodejs,urn:cnb:builder:heroku/python` to use the builders built-in buildpacks and am still seeing this delay.

Looking at the log lines before, it appears the last command before the delay is:

```
Running the 'creator' on OS 'linux' with:
--
Args: '/cnb/lifecycle/creator -log-level debug -app /workspace -cache-dir /cache -run-image registry.apppackcdn.net/heroku/heroku:20-cnb -tag xxx.dkr.ecr.us-east-2.amazonaws.com/myrepo:build-9 -tag xxx.dkr.ecr.us-east-2.amazonaws.com/myrepo:8c66ae9650215f36d6b8d5635dba8d91bf117904 -gid 0 -previous-image xxx.dkr.ecr.us-east-2.amazonaws.com/myrepo:latest -cache-image xxx.dkr.ecr.us-east-2.amazonaws.com/myrepo:cache xxx.dkr.ecr.us-east-2.amazonaws.com/myrepo:latest
```

I'm wondering if this is when it is pulling down the previous and cache images which could explain the delay.

**Comment by jjbustamante** [comment] 2023-08-16 18:34
Hi @ipmb 

We will fix an issue #1732 in pack 0.30 which **could** be related to this one, could you try this scenario with the 0.30.0-RC2 version and let us know if it is solved in that version?

**Comment by jjbustamante** [comment] 2023-08-16 18:35
Duplicate of #1577

**Comment by jjbustamante** [comment] 2023-08-16 18:36
I'm gonna close this one as duplicated

**Closed by jjbustamante** 2023-08-16 18:36 UTC
Labels: type/bug, status/in-progress
