### ISSUE TITLE
Pack export fails with: failed to export: previous image did not have layer with sha ''

### ISSUE THREAD

**Issue by josephlewis42** [buildpacks/pack#336] opened 2019-10-08 21:15 UTC
I have a buildpack builder image that works locally via pack but fails when the lifecycle components are called in a remote pipeline. The error I'm seeing is the following during the export step:

```
Exporting layer 'app' with SHA sha256:eb95b8187adb5e960c872773e4f1c4880cfd51a464b421883f9afad845f3abc5
Exporting layer 'config' with SHA sha256:78e1da51ad817604babfeb24d453799758af7df1aa8daeb3292e52c71240cc08
Exporting layer 'launcher' with SHA sha256:ef2cd5869b4d3995edbba8144c8c448f864f3895ea264967701a9a97547d6087
Exporting layer 'org.cloudfoundry.openjdk:openjdk-jre' with SHA sha256:53458213bcc7428b157f62fd41524f2fa44e6808c091c333bb94d70436e5e23a
Reusing layer 'org.cloudfoundry.tomcat:catalina-base' with SHA 
Error: failed to export: previous image did not have layer with sha ''
```

## Steps to reproduce

Create a builder:

```
description = "Sample builder"

[[buildpacks]]
id = "org.cloudfoundry.archiveexpanding"
uri = "https://storage.googleapis.com/cnb-buildpacks/archive-expanding-cnb/org.cloudfoundry.archiveexpanding-1.0.51.tgz"

[[buildpacks]]
id = "org.cloudfoundry.openjdk"
uri = "https://storage.googleapis.com/cnb-buildpacks/openjdk-cnb/org.cloudfoundry.openjdk-1.0.26.tgz"

[[buildpacks]]
id = "org.cloudfoundry.jvmapplication"
uri = "https://storage.googleapis.com/cnb-buildpacks/jvm-application-cnb/org.cloudfoundry.jvmapplication-1.0.41.tgz"

[[buildpacks]]
id = "org.cloudfoundry.tomcat"
uri = "https://storage.googleapis.com/cnb-buildpacks/tomcat-cnb/org.cloudfoundry.tomcat-1.0.66.tgz"

[[order]]
group = [
  ### Builders, order is meaningful
  { id = "org.cloudfoundry.archiveexpanding", optional = true },
  { id = "org.cloudfoundry.openjdk" },
  { id = "org.cloudfoundry.jvmapplication" },

  ### Runtimes, ordered by priority
  { id = "org.cloudfoundry.tomcat", optional = true },
]

[stack]
id = "io.buildpacks.stacks.bionic"
run-image = "gcr.io/kf-releases/run:latest"
build-image = "gcr.io/kf-releases/build:latest"
```

Create the builder:

```
pack create-builder --builder-config builder.toml  --publish gcr.io/kf-releases/bad-builder
```

Create a sample WAR file to try building:

```
git clone https://github.com/cloudfoundry/java-test-applications/tree/master/web-servlet-2-application
cd web-servlet-2-application
gradle build
cd build/libs
```

Build locally (this works):

```
$ pack build passlocal/passlocal --builder gcr.io/kf-releases/bad-builder
Pulling image gcr.io/kf-releases/bad-builder:latest

<snip>

===> EXPORTING
[exporter] Exporting layer 'app' with SHA sha256:8bf4e61b536076f534cc388c3e5994fbf0bd4f045b7a572c160fa6d435692fbd
[exporter] Exporting layer 'config' with SHA sha256:7a85156ee2192ccbd71bde9685da1d3b0c3049fb2907de0cce7f9634e3283127
[exporter] Exporting layer 'launcher' with SHA sha256:ef2cd5869b4d3995edbba8144c8c448f864f3895ea264967701a9a97547d6087
[exporter] Exporting layer 'org.cloudfoundry.openjdk:openjdk-jre' with SHA sha256:c01d3108656d9135fa72131e2e7be2122ff54d7684565aa8ef88682ade2a3781
[exporter] Exporting layer 'org.cloudfoundry.tomcat:catalina-base' with SHA sha256:d6ab8b4fc68c33e1ae484104e5dae7932e249a936ae66ad11f697d80e9943bca
[exporter] Exporting layer 'org.cloudfoundry.tomcat:tomcat' with SHA sha256:c6cf8118099562529f6503e3bd0c34a600485f1ffab01c7be7543c7348f53fe9
[exporter] *** Images:
[exporter]       index.docker.io/passlocal/passlocal:latest - succeeded
[exporter] 
[exporter] *** Image ID: 91a5513b55e78b7e1403ca12009b45cdb64edb0d808b781c2b36273f0958c788
===> CACHING
Successfully built image passlocal/passlocal
```

Try building remotely with a Knative Build pipeline, the build is the same but the export step fails:

```
Exporting layer 'app' with SHA sha256:eb95b8187adb5e960c872773e4f1c4880cfd51a464b421883f9afad845f3abc5
Exporting layer 'config' with SHA sha256:78e1da51ad817604babfeb24d453799758af7df1aa8daeb3292e52c71240cc08
Exporting layer 'launcher' with SHA sha256:ef2cd5869b4d3995edbba8144c8c448f864f3895ea264967701a9a97547d6087
Exporting layer 'org.cloudfoundry.openjdk:openjdk-jre' with SHA sha256:53458213bcc7428b157f62fd41524f2fa44e6808c091c333bb94d70436e5e23a
Reusing layer 'org.cloudfoundry.tomcat:catalina-base' with SHA 
Error: failed to export: previous image did not have layer with sha ''
```

The container that failed has the following setup:

```
- args:
  - -layers=/layers
  - -helpers=true
  - -app=/workspace
  - -image=
  - -group=/layers/group.toml
  - gcr.io/kf-source/app_joseph_badapp:0
  command:
  - /lifecycle/exporter
  env:
  - name: HOME
    value: /builder/home
  image: gcr.io/kf-releases/bad-builder
  imagePullPolicy: Always
  name: build-step-export
  resources: {}
  terminationMessagePath: /dev/termination-log
  terminationMessagePolicy: File
  volumeMounts:
  - mountPath: /layers
    name: empty-dir
  - mountPath: /workspace
    name: workspace
  - mountPath: /builder/home
    name: home
  - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
    name: default-token-wlwh4
    readOnly: true
  workingDir: /workspace
```

Versions:

```
$ pack version
v0.4.1 (git sha: 90e88e7b1dc02ca65e22548fdfbeabec4c9879a6)

$ pack inspect-builder gcr.io/kf-releases/bad-builder
Inspecting builder: gcr.io/kf-releases/bad-builder

Remote
------

Description: Sample failing builder

Stack: io.buildpacks.stacks.bionic

Lifecycle:
  Version: 0.4.0
  Buildpack API: 0.2
  Platform API: 0.1
<snip>
```

**Comment by jromero** [comment] 2019-10-09 13:45
@josephlewis42 we can see how the issue could occur in the code base but trying to reproduce the issue locally. This would help us ensure this is the case and hopefully get you past this issue.

We noticed that the `sha`s for the knative execution and the `pack` execution differ. Are you able to share what the other phase executions look like in your knative pipeline?

**Comment by josephlewis42** [comment] 2019-10-09 18:55
@jromero sure! Here are the logs I get back from the build. The custom-source step is a self-extracting docker image.

```
[build-step-credential-initializer] {"level":"warn","ts":1570646904.6041458,"logger":"fallback-logger","caller":"logging/config.go:65","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/upstream/release-0.6\" is not a valid GitHub commit ID"}
[build-step-credential-initializer] {"level":"info","ts":1570646904.6046941,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}
[build-step-custom-source] 2019/10/09 18:48:25 Done!
[build-step-prepare] web-servlet-2-application-1.0.0.BUILD-SNAPSHOT.war
[build-step-detect] ======== Results ========
[build-step-detect] pass: org.cloudfoundry.archiveexpanding@1.0.51
[build-step-detect] pass: org.cloudfoundry.openjdk@1.0.26
[build-step-detect] pass: org.cloudfoundry.jvmapplication@1.0.41
[build-step-detect] pass: org.cloudfoundry.tomcat@1.0.66
[build-step-detect] Resolving plan... (try #1)
[build-step-detect] fail: org.cloudfoundry.openjdk@1.0.26 provides unused openjdk-jdk
[build-step-detect] Resolving plan... (try #2)
[build-step-detect] fail: org.cloudfoundry.jvmapplication@1.0.41 requires openjdk-jre
[build-step-detect] Resolving plan... (try #3)
[build-step-detect] Success! (4)
[build-step-analyze] Image 'gcr.io/GCP_PROJECT/app_joseph_test:4' not found
[build-step-build] 
[build-step-build] Cloud Foundry Archive Expanding Buildpack 1.0.51
[build-step-build]     Expanding /workspace/web-servlet-2-application-1.0.0.BUILD-SNAPSHOT.war to /workspace
[build-step-build]     Removing  /workspace/web-servlet-2-application-1.0.0.BUILD-SNAPSHOT.war
[build-step-build] 
[build-step-build] Cloud Foundry OpenJDK Buildpack 1.0.26
[build-step-build]   OpenJDK JRE 11.0.4: Contributing to layer
[build-step-build]     Reusing cached download from buildpack
[build-step-build]     Expanding to /layers/org.cloudfoundry.openjdk/openjdk-jre
[build-step-build]     Writing JAVA_HOME to shared
[build-step-build] 
[build-step-build] Cloud Foundry Apache Tomcat Buildpack 1.0.66
[build-step-build]   Apache Tomcat Support 3.3.0: Contributing to layer
[build-step-build]   Contributing Configuration
[build-step-build]     Copying context.xml to /layers/org.cloudfoundry.tomcat/catalina-base/conf
[build-step-build]     Copying logging.properties to /layers/org.cloudfoundry.tomcat/catalina-base/conf
[build-step-build]     Copying server.xml to /layers/org.cloudfoundry.tomcat/catalina-base/conf
[build-step-build]     Copying web.xml to /layers/org.cloudfoundry.tomcat/catalina-base/conf
[build-step-build]   Contributing Access Logging Support
[build-step-build]     Reusing cached download from buildpack
[build-step-build]     Copying to /layers/org.cloudfoundry.tomcat/catalina-base/lib
[build-step-build]     Writing .profile.d/access-logging
[build-step-build]   Contributing Lifecycle Support
[build-step-build]     Reusing cached download from buildpack
[build-step-build]     Copying to /layers/org.cloudfoundry.tomcat/catalina-base/lib
[build-step-build]   Contributing Logging Support
[build-step-build]     Reusing cached download from buildpack
[build-step-build]     Copying to /layers/org.cloudfoundry.tomcat/catalina-base/bin
[build-step-build]     Writing /layers/org.cloudfoundry.tomcat/catalina-base/bin/setenv.sh
[build-step-build]   Mounting application at /layers/org.cloudfoundry.tomcat/catalina-base/webapps/ROOT
[build-step-build]     Writing CATALINA_BASE to launch
[build-step-build]   Apache Tomcat 9.0.26: Contributing to layer
[build-step-build]     Reusing cached download from buildpack
[build-step-build]     Extracting to /layers/org.cloudfoundry.tomcat/tomcat
[build-step-build]     Writing CATALINA_HOME to launch
[build-step-build]   Process types:
[build-step-build]     task:   catalina.sh run
[build-step-build]     tomcat: catalina.sh run
[build-step-build]     web:    catalina.sh run
[build-step-export] Exporting layer 'app' with SHA sha256:eb95b8187adb5e960c872773e4f1c4880cfd51a464b421883f9afad845f3abc5
[build-step-export] Exporting layer 'config' with SHA sha256:78e1da51ad817604babfeb24d453799758af7df1aa8daeb3292e52c71240cc08
[build-step-export] Exporting layer 'launcher' with SHA sha256:ef2cd5869b4d3995edbba8144c8c448f864f3895ea264967701a9a97547d6087
[build-step-export] Exporting layer 'org.cloudfoundry.openjdk:openjdk-jre' with SHA sha256:53458213bcc7428b157f62fd41524f2fa44e6808c091c333bb94d70436e5e23a
[build-step-export] Reusing layer 'org.cloudfoundry.tomcat:catalina-base' with SHA 
[build-step-export] Error: failed to export: previous image did not have layer with sha ''

```


The clusterbuildtemplate is:

```
apiVersion: build.knative.dev/v1alpha1
kind: ClusterBuildTemplate
metadata:
  annotations:
  creationTimestamp: "2019-05-29T19:25:44Z"
  generation: 83
  name: buildpack
  resourceVersion: "72332371"
  selfLink: /apis/build.knative.dev/v1alpha1/clusterbuildtemplates/buildpack
  uid: 8dddf14c-8247-11e9-aeb4-42010a8000b5
spec:
  parameters:
  - description: The image you wish to create. For example, "repo/example", or "example.com/repo/image"
    name: IMAGE
  - default: packs/run:v3alpha2
    description: The run image buildpacks will use as the base for IMAGE.
    name: RUN_IMAGE
  - default: gcr.io/kf-releases/buildpack-builder:latest
    description: The builder image (must include v3 lifecycle and compatible buildpacks).
    name: BUILDER_IMAGE
  - default: "true"
    description: Use Docker credential helpers for Googles GCR, Amazons ECR, or Microsofts
      ACR.
    name: USE_CRED_HELPERS
  - default: empty-dir
    description: The name of the persistent app cache volume
    name: CACHE
  - default: "1000"
    description: The user ID of the builder image user
    name: USER_ID
  - default: "1000"
    description: The group ID of the builder image user
    name: GROUP_ID
  - default: ""
    description: When set, skip the detect step and use the given buildpack.
    name: BUILDPACK
  steps:
  - args:
    - -c
    - |
      chown -R "${USER_ID}:${GROUP_ID}" "/builder/home" \
        && chown -R "${USER_ID}:${GROUP_ID}" /layers \
                                            && chown -R "${USER_ID}:${GROUP_ID}" /workspace && ls /workspace
    command:
    - /bin/sh
    image: alpine
    imagePullPolicy: Always
    name: prepare
    resources: {}
    volumeMounts:
    - mountPath: /layers
      name: ${CACHE}
  - args:
    - -c
    - |
      if [[ -z "${BUILDPACK}" ]]; then
        /lifecycle/detector \
          -app=/workspace \
          -group=/layers/group.toml \
          -plan=/layers/plan.toml
      else
        touch /layers/plan.toml
        echo -e "[[buildpacks]]\nid = \"${BUILDPACK}\"\nversion = \"latest\"\n" > /layers/group.toml
      fi
    command:
    - /bin/bash
    image: ${BUILDER_IMAGE}
    imagePullPolicy: Always
    name: detect
    resources: {}
    volumeMounts:
    - mountPath: /layers
      name: ${CACHE}
  - args:
    - -layers=/layers
    - -helpers=${USE_CRED_HELPERS}
    - -group=/layers/group.toml
    - ${IMAGE}
    command:
    - /lifecycle/analyzer
    image: ${BUILDER_IMAGE}
    imagePullPolicy: Always
    name: analyze
    resources: {}
    volumeMounts:
    - mountPath: /layers
      name: ${CACHE}
  - args:
    - -layers=/layers
    - -app=/workspace
    - -group=/layers/group.toml
    - -plan=/layers/plan.toml
    command:
    - /lifecycle/builder
    image: ${BUILDER_IMAGE}
    imagePullPolicy: Always
    name: build
    resources: {}
    volumeMounts:
    - mountPath: /layers
      name: ${CACHE}
  - args:
    - -layers=/layers
    - -helpers=${USE_CRED_HELPERS}
    - -app=/workspace
    - -image=${RUN_IMAGE}
    - -group=/layers/group.toml
    - ${IMAGE}
    command:
    - /lifecycle/exporter
    image: ${BUILDER_IMAGE}
    imagePullPolicy: Always
    name: export
    resources: {}
    volumeMounts:
    - mountPath: /layers
      name: ${CACHE}
  volumes:
  - name: empty-dir

```

The pod was:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    sidecar.istio.io/inject: "false"
  creationTimestamp: "2019-10-09T18:48:22Z"
  labels:
    app.kubernetes.io/component: build
    app.kubernetes.io/managed-by: kf
    app.kubernetes.io/name: test
    build.knative.dev/buildName: test-4
  name: test-4-pod-31dfa9
  namespace: joseph
  ownerReferences:
  - apiVersion: build.knative.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Build
    name: test-4
    uid: 5e469241-eac5-11e9-b478-42010a8000dd
  resourceVersion: "72332577"
  selfLink: /api/v1/namespaces/joseph/pods/test-4-pod-31dfa9
  uid: 5e4ea352-eac5-11e9-b478-42010a8000dd
spec:
  containers:
  - image: gcr.io/knative-releases/github.com/knative/build/cmd/nop@sha256:50e2be042298f24800b9840a9aef831a5fe4d89d9a8edea5e0559cdedf32369d
    imagePullPolicy: IfNotPresent
    name: nop
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-wlwh4
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - env:
    - name: HOME
      value: /builder/home
    image: gcr.io/knative-releases/github.com/knative/build/cmd/creds-init@sha256:101f537b53b895b28b84ac3c74ede7d250845e24c51c26516873d8ccb23168ce
    imagePullPolicy: IfNotPresent
    name: build-step-credential-initializer
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /workspace
      name: workspace
    - mountPath: /builder/home
      name: home
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-wlwh4
      readOnly: true
    workingDir: /workspace
  - env:
    - name: HOME
      value: /builder/home
    image: gcr.io/GCP_PROJECT/src-joseph-test:1570646899644718254
    imagePullPolicy: IfNotPresent
    name: build-step-custom-source
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /workspace
      name: workspace
    - mountPath: /builder/home
      name: home
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-wlwh4
      readOnly: true
    workingDir: /workspace
  - args:
    - -c
    - |
      chown -R "1000:1000" "/builder/home" \
        && chown -R "1000:1000" /layers \
                                            && chown -R "1000:1000" /workspace && ls /workspace
    command:
    - /bin/sh
    env:
    - name: HOME
      value: /builder/home
    image: alpine
    imagePullPolicy: Always
    name: build-step-prepare
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /layers
      name: empty-dir
    - mountPath: /workspace
      name: workspace
    - mountPath: /builder/home
      name: home
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-wlwh4
      readOnly: true
    workingDir: /workspace
  - args:
    - -c
    - |
      if [[ -z "" ]]; then
        /lifecycle/detector \
          -app=/workspace \
          -group=/layers/group.toml \
          -plan=/layers/plan.toml
      else
        touch /layers/plan.toml
        echo -e "[[buildpacks]]\nid = \"\"\nversion = \"latest\"\n" > /layers/group.toml
      fi
    command:
    - /bin/bash
    env:
    - name: HOME
      value: /builder/home
    image: gcr.io/kf-releases/bad-builder
    imagePullPolicy: Always
    name: build-step-detect
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /layers
      name: empty-dir
    - mountPath: /workspace
      name: workspace
    - mountPath: /builder/home
      name: home
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-wlwh4
      readOnly: true
    workingDir: /workspace
  - args:
    - -layers=/layers
    - -helpers=true
    - -group=/layers/group.toml
    - gcr.io/GCP_PROJECT/app_joseph_test:4
    command:
    - /lifecycle/analyzer
    env:
    - name: HOME
      value: /builder/home
    image: gcr.io/kf-releases/bad-builder
    imagePullPolicy: Always
    name: build-step-analyze
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /layers
      name: empty-dir
    - mountPath: /workspace
      name: workspace
    - mountPath: /builder/home
      name: home
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-wlwh4
      readOnly: true
    workingDir: /workspace
  - args:
    - -layers=/layers
    - -app=/workspace
    - -group=/layers/group.toml
    - -plan=/layers/plan.toml
    command:
    - /lifecycle/builder
    env:
    - name: HOME
      value: /builder/home
    image: gcr.io/kf-releases/bad-builder
    imagePullPolicy: Always
    name: build-step-build
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /layers
      name: empty-dir
    - mountPath: /workspace
      name: workspace
    - mountPath: /builder/home
      name: home
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-wlwh4
      readOnly: true
    workingDir: /workspace
  - args:
    - -layers=/layers
    - -helpers=true
    - -app=/workspace
    - -image=
    - -group=/layers/group.toml
    - gcr.io/GCP_PROJECT/app_joseph_test:4
    command:
    - /lifecycle/exporter
    env:
    - name: HOME
      value: /builder/home
    image: gcr.io/kf-releases/bad-builder
    imagePullPolicy: Always
    name: build-step-export
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /layers
      name: empty-dir
    - mountPath: /workspace
      name: workspace
    - mountPath: /builder/home
      name: home
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-wlwh4
      readOnly: true
    workingDir: /workspace
  nodeName: gke-kf-2-default-pool-3d290631-xx5v
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: empty-dir
  - emptyDir: {}
    name: workspace
  - emptyDir: {}
    name: home
  - name: default-token-wlwh4
    secret:
      defaultMode: 420
      secretName: default-token-wlwh4

```

The build template is a bit old, but I also tried an updated version based on tekton https://github.com/google/kf/pull/746/files and it also failed with the same error.

**Comment by evandbrown** [comment] 2019-10-24 14:08
Hi @jromero, is there anything else we can provide to help identify and resolve this issue?

**Comment by ameyer-pivotal** [comment] 2019-10-24 14:49
@evandbrown We're working to reproduce the issue. Could you provide the `Build` yaml that you applied to kick off the build?

**Comment by ameyer-pivotal** [comment] 2019-10-24 16:13
@evandbrown A couple of things:

- It seems your builder has changed, as it no longer gets through detect
- Can you run `docker inspect` on your previous app image and paste the output? We specifically are interested in the contents of the `io.buildpacks.lifecycle.metadata` label (we think this is ultimately where the empty SHA is coming from).

**Comment by jromero** [comment] 2019-11-13 16:10
It looks like the error could be closely related to https://github.com/buildpack/lifecycle/pull/211. That function is used in `exporter` as well and could very well be the underlying issue in that it's obfuscating an underlying error.

Could you try lifecycle from `master` and see if it changes the results?

**Comment by natalieparellano** [comment] 2020-02-05 22:21
@evandbrown is this still an issue?

**Comment by natalieparellano** [comment] 2020-02-06 20:18
Closing this for now, but feel free to reopen this issue if it's still a problem.

**Closed by natalieparellano** 2020-02-06 20:18 UTC
Labels: status/awaiting-response, triage/review, type/bug, type/support
