### ISSUE TITLE
pack should respect current docker context

### ISSUE THREAD

**Issue by jabrown85** [buildpacks/pack#1830] opened 2023-07-06 14:42 UTC
### Summary

It looks like `pack` is not defaulting to the _current_ context, according to `docker context list`.

---

##### Steps

1. Install Docker Desktop
2. `pack build`
3. See error

I'm not entirely sure if _every_ install gets 2 contexts or how I came to have two contexts. Confusingly, the one named `default` is _not_ the current one. Regardless, I think `Current:  true` one should be used without having to exported. 

##### Current behavior

```
➜  go-getting-started git:(main) pack build gotest
ERROR: failed to build: failed to fetch builder image 'index.docker.io/heroku/builder:22': Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
➜  go-getting-started git:(main) docker context list
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                                     KUBERNETES ENDPOINT   ORCHESTRATOR
default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock
desktop-linux *     moby                Docker Desktop                            unix:///Users/jesse.brown/.docker/run/docker.sock
➜  go-getting-started git:(main) export DOCKER_HOST=unix:///Users/jesse.brown/.docker/run/docker.sock
➜  go-getting-started git:(main) pack build gotest
22: Pulling from heroku/builder
9d19ee268e0d: Already exists
304bc4ffd583: Pull complete
cbc89d407835: Downloading [=========>                                         ]  37.61MB/208.7MB
1c3886ee831f: Download complete
c48649843400: Downloading [=============>                                     ]  31.64MB/115.8MB
1d10fe0ff495: Download complete
94fbeab652fb: Download complete
70e0bea64ce8: Download complete
eac4c70d6d1c: Downloading [===============>                                   ]  3.185MB/10.34MB
```

##### Expected behavior

I expected `pack build` to work without any additional configuration.

---

##### pack info

```
Pack:
  Version:  0.28.0+git-b10e41f.build-3729
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.15.2

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10

Config:
  default-builder-image = "[REDACTED]"
  experimental = true

  [[trusted-builders]]
    name = "[REDACTED]"

  [[trusted-builders]]
    name = "[REDACTED]"
```

##### docker info

```
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /Users/jesse.brown/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /Users/jesse.brown/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/jesse.brown/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /Users/jesse.brown/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /Users/jesse.brown/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/jesse.brown/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/jesse.brown/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.12.0
    Path:     /Users/jesse.brown/.docker/cli-plugins/docker-scout

Server:
 Containers: 458
  Running: 1
  Paused: 0
  Stopped: 457
 Images: 293
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit-pr
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.64GiB
 Name: docker-desktop
 ID: 443b6e33-3385-4db7-8928-e2ff4057a16f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: true
 Insecure Registries:
   ...snip...  
 Live Restore Enabled: false
```

**Comment by jjbustamante** [comment] 2023-08-14 15:53
Looking into this, we need to go to this [place](https://github.com/buildpacks/pack/blob/main/internal/build/phase_config_provider.go#L155) and try to add some logic to ask Docker the host configured and use that one if DOCKER_HOST env is empty.

**Comment by jjbustamante** [comment] 2023-08-15 19:26
Duplicate of #1759

**Comment by natalieparellano** [comment] 2023-08-23 17:57
Closing in favor of https://github.com/buildpacks/pack/issues/1759

**Closed by natalieparellano** 2023-08-23 17:57 UTC
Labels: type/bug, size/sm, status/ready

**Comment by jjbustamante** [comment] 2023-09-20 15:02
Hi @jabrown85 

We just released a [RC](https://github.com/buildpacks/pack/releases/tag/v0.31.0-rc1) pack version, it will be great if you can give it a try and confirm the issue was solved

**Comment by jabrown85** [comment] 2023-09-20 15:18
@jjbustamante - that worked for me! I was able to `unset DOCKER_HOST` and `~/Downloads/pack build blah` with the RC. Thanks for the fix!
