### ISSUE TITLE
Implement cache flag in pack

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#1458] opened 2022-06-15 16:02 UTC
Implement a basic flag `--cache`, that the project revolves around.
This flag will be implement such that it supports sensible defaults for the current state of pack while also being extensible for the future additions that will be coming in.

Eg -
```bash
pack build --cache 'type=build;format=bind;source=./my-build-cache'
```

An alternate way suggested in the RFC was to use simpler flags, if we decide on using them then this task will progress as the other things in the project get implemented.

@imnitishng:
#### Selected approach (what I have selected, this hasn't been discussed with the mentor yet)

I feel like implementing a single `--cache` flag with variadic options is a better option, if documented concisely this would be cleaner in my opinion.

**Comment by jromero** [comment] 2022-06-15 16:03
@imnitishng, Glad to hear you agree with the RFC. That is what we'd like to implement as per this section of the RFC: https://github.com/buildpacks/rfcs/blob/main/text/0091-pack-cache-options.md#what-it-is

I wonder if this task should be to implement "volume" format of cache for build given that it's the current default. "bind" is a new format that would need to be implemented.

**Comment by imnitishng** [comment] 2022-06-17 11:47
> I wonder if this task should be to implement "volume" format of cache for build given that it's the current default.

The task was actually just meant to be a draft task to implement just the `--cache` flag (without any cache logic implementation), now that the issue is not draft it seems more like a tiny milestone.

> I wonder if this task should be to implement "volume" format of cache 

We can have a new issue for it, for now I we will probably close this issue soon, once it is implemented.

> "bind" is a new format that would need to be implemented.

Yes, agreed! That is planned to be worked in the last phase of the project.

**Closed** 2022-06-17 13:39 UTC
Labels: status/invalid
