### ISSUE TITLE
Pack not working with windows stack

### ISSUE THREAD

**Issue by macsux** [buildpacks/pack#1392] opened 2022-03-16 16:16 UTC
### Summary
Attempt to use windows stack as described [here](https://buildpacks.io/docs/app-developer-guide/build-a-windows-app/) fails as following
```
pack build funnyquotes-formsui --path . --builder cnbs/sample-builder:dotnet-framework-1809 --trust-builder
dotnet-framework-1809: Pulling from cnbs/sample-builder
Digest: sha256:15b485b28b7a5fea8a8dbbbd5259f0d8da1023b86015f71335a8f14b6582a18a
Status: Image is up to date for cnbs/sample-builder:dotnet-framework-1809
dotnet-framework-1809: Pulling from cnbs/sample-stack-run
Digest: sha256:2735d59e7a849f33c71b14d269377f6736d8d0863bb7e419bc194923737ea17c
Status: Image is up to date for cnbs/sample-stack-run:dotnet-framework-1809
ERROR: failed to build: executing lifecycle: container start: Error response from daemon: hcsshim::CreateComputeSystem 0992c2ff21e0b272849e096f7821e81a26baf1dae39a4f58ab39bc2f53257aac: The container operating system does not match the host operating system.
```

### Reproduction

Try to follow the instructions described here https://buildpacks.io/docs/app-developer-guide/build-a-windows-app/

##### Current behavior
Error

##### Expected behavior
Container creates successfuly

---

##### pack info
```
Pack:
  Version:  0.24.0+git-79a40b7.build-3148
  OS/Arch:  windows/amd64

Default Lifecycle Version:  0.13.3

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6, 0.7, 0.8

Config:
  default-builder-image = "[REDACTED]"
  experimental = true
```

##### docker info
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.0)
  compose: Docker Compose (Docker Inc., v2.3.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 115
  Running: 0
  Paused: 0
  Stopped: 115
 Images: 340
 Server Version: 20.10.13
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19043 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Enterprise Version 2009 (OS Build 19043.1586)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.81GiB
 Name: DRAKE
 ID: 3VBS:BAXF:RH4W:GZ3H:3DGP:5OFB:3OCO:UPD5:XDF7:67ZW:IA6K:KMIC
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by natalieparellano** [comment] 2022-03-17 13:51
Adding some info communicated out of band - 

`pack build --lifecycle-image buildpacksio/lifecycle:0.13.3`  (without `--trust-builder`) leads to `The container operating system does not match the host operating system`.

However `docker run buildpacksio/lifecycle:0.13.3` executes successfully.

Therefore the issue seems to be a difference in how pack is starting containers vs. how docker is starting containers.

One possible culprit: the [container host config](https://github.com/buildpacks/pack/blob/70fb6784038fe6cecce8603c973f38875a4a3000/internal/build/container_ops.go#L141) used by pack. Process isolation is hard coded, whereas `docker info` above indicates `Default Isolation: hyperv`. We should investigate why process isolation is hard coded and what would be the implications of switching (if this is indeed the issue). It's worth noting that hyperv is required to enable Windows Subsystem for Linux, so asking pack users to disable it is probably not a viable option.

**Comment by jromero** [comment] 2022-03-24 14:09
Update: Started looking into this yesterday but to be honest, it may take a while just to even reproduce. At the moment, I tried to reuse a Windows 2019 workstation we had available but in trying to switch it to hyperv isolation it got hosed. I'll try to procure a appropriate machine.

**Comment by jromero** [comment] 2022-03-24 15:49
@macsux while we try to reproduce it do you think you could try recompiling pack locally and changing all references of [`IsolationProcess`](https://github.com/buildpacks/pack/search?q=IsolationProcess) to `IsolationHyperV` or `IsolationDefault` ([defined here](https://github.com/moby/moby/blob/0798f5f5cf6908593472b21179360168cd9f4691/api/types/container/host_config.go#L48-L53)). This would at least help us validate or cross-off @ekcasey's assessment.

**Comment by jromero** [comment] 2022-03-31 17:25
**Update:**

Here's what I've found thus far...

1. The primary reason why this is a doesn't work on Windows 10 Enterprise (21H2) with process isolation is primarily to do with [this](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2019%2Cwindows-11-21H2#windows-client-host-os-compatibility):
    > The architecture of Windows differs vastly from that of Linux. Linux has a monolithic kernel, while in Windows User and Kernel mode are more tightly bound.
    <img width="735" alt="image" src="https://user-images.githubusercontent.com/475559/161107599-f1cc5631-5174-4b8d-a41c-5f03834b5ed8.png">
1. Based on the chart above, you will find that there is a process isolation compatible image that could work (Windows Server 2022). To add more complexity to the compatibility though, you would then need to look at [build numbers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2019%2Cwindows-11-21H2#build-number-new-release-of-windows) as well. For example, attempting to run `mcr.microsoft.com/windows/servercore:ltsc2022-amd64` yields:
    >  a Windows version 10.0.20348-based image is incompatible with a 10.0.19044 host

    My version:
    ```
    Kernel Version: 10.0 19044 (19041.1.amd64fre.vb_release.191206-1406)
    Operating System: Windows 10 Enterprise LTSC 2021 Evaluation Version 2009 (OS Build 19044.1586)
    ```
1. Fortunately, there's a [version of servercore](https://hub.docker.com/_/microsoft-windows-servercore) out there that did work `mcr.microsoft.com/windows/servercore:10.0.19041.1415`:
    ```
    docker run --rm -it --isolation=process --entrypoint=cmd.exe mcr.microsoft.com/windows/servercore:10.0.19041.1415
    ```

This is just a quick update of the research thus far, there are a couple routes that still need to be explored.

1. Why doesn't hyper-v isolation work for us? Currently, error out with `Access is denied.`
    - The answer to this may lie in how the [different isolations work](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/hyperv-container#isolation-explanation). The current hypothesis is that certain limitation brought on by hyper-v are obstructing necessary services (ie. volume mounts, docker pipe, etc).
2. Create a dotnet-framework builder that works on 1904x (aka [2004(?)](https://support.microsoft.com/en-us/topic/windows-10-update-history-24ea91f4-36e7-d8fd-0ddb-d79d9d0cdbda))

**Comment by jromero** [comment] 2022-04-04 22:53
Based on 2) above I've got a few PR's up and was able to produce a build on the prior non-working environment.

- https://github.com/buildpacks/samples/pull/117
- https://github.com/buildpacks/docs/pull/486

@macsux if you could verify that this works for you, I could merged both of those in.

**Closed** 2022-04-06 18:16 UTC
Labels: type/bug, status/ready
