### ISSUE TITLE
sign container images after built

### ISSUE THREAD

**Issue by developer-guy** [buildpacks/pack#1443] opened 2022-05-13 07:03 UTC
### Description

We (w/@dentrax) thought that it'd be nice if pack CLI has the support of signing container images right after building them without requiring any additional steps to sign container images based on cosign, a tool developed by the sigstore community that lets you sign, and verify container images according to several types of key management types, or any other signing tool. 

### Proposed solution

Maybe we can add additional flag to the build command in pack CLI to enable signing, it'll be look like this:

```shell
# Set default signer to the config
$ paketo config default-signer cosign
```

```shell
# it'll sign container image right after built
$ pack build --signer cosign <img>
```

### Additional context
- [x] This feature should be documented somewhere

**Comment by developer-guy** [comment] 2022-06-06 19:08
kindly ping @samj

**Comment by samj1912** [comment] 2022-06-07 09:29
Related https://github.com/buildpacks/rfcs/pull/195  and https://github.com/buildpacks/pack/issues/268#issuecomment-973623399

@developer-guy

**Comment by samj1912** [comment] 2022-06-07 09:32
(Accidentally closed, reopened again)

**Comment by Gauravkumar2701** [comment] 2022-12-27 17:59
@developer-guy @samj1912 @Dentrax Guys I also want to work on this issue @developer-guy could you please guide me with more information.

**Comment by natalieparellano** [comment] 2023-08-18 19:18
Closing as duplicate of https://github.com/buildpacks/pack/issues/268

**Closed by natalieparellano** 2023-08-18 19:18 UTC
Labels: type/enhancement, help wanted, status/ready
