### ISSUE TITLE
If Dockerfile is present at the root, perform a regular Docker build

### ISSUE THREAD

**Issue by steren** [buildpacks/pack#756] opened 2020-07-18 15:52 UTC
Today, running `pack build --builder gcr.io/buildpacks/builder` in a repo that contains code written in popular languages will result in a nice container for these languages.
Sadly, if this repo contains a `Dockerfile`, then the command will ignore it and still do a language detection.
This means that developers now have to change their tooling (`pack` vs `docker`) depending on the kind of build they want to perform.

It would be simpler if `pack build` would detect the presence of the `Dockerfile` and trigger a regular docker build if present (taking priority over any Buildpack detection)

This would greatly simplify the onboarding of products like Google Cloud Run or setting up Continuous Deployment: developers would simply always use `pack` instead of having to decide between `pack` and `docker`

According to https://github.com/GoogleCloudPlatform/buildpacks/issues/62, this is not something that can be done *inside* a buildpack, so I suggest we add this behavior to the `pack` command itself, for convenience.

**Comment by sclevine** [comment] 2020-07-20 14:24
A few counterpoints:

The user would lose the benefits of the Cloud Native Buildpacks model, like rebasing and reproducible image builds. In general, I'm not convinced that users would want use the pack CLI but expect not to use the Cloud Native Buildpacks project while using it.

Also, this makes the assumption that a Dockerfile at the root of the app implies that the user doesn't want to use the Cloud Native Buildpacks project. They might actually intend to build the app using CNB, even if they put a Dockerfile at the root for other purposes.

Finally, the pack CLI just uses the Docker daemon as a container runtime, and only because it's easy to install on Windows or Mac. We may not use Docker in the future (especially on Linux), and Docker is currently not used by non-local platforms like the Tekton template or kpack. To implement this consistently, we'd need to pull kaniko into the lifecycle. (To be fare, we already plan to do this to support app mixins.)

**Comment by jamesward** [comment] 2020-07-20 14:33
Instead of building this into `pack` it'd be interesting to explore a `Dockerfile` buildpack.  That way platforms that want to have this behavior could.  Kaniko might be a way to implement it.

**Comment by ameyer-pivotal** [comment] 2020-07-20 15:35
Just saw the note about it not being possible inside a buildpack. Will definitely read that...

**Comment by jromero** [comment] 2020-07-20 15:40
Certain things would be possible within a buildpack. I think the comment about not being possible are more associated with executing the Dockerfile against the docker daemon (which isn't accessible from a buildpack) BUT if you could transpose the Dockerfile to operations that yield layers, labels, etc then it would work for _certain_ scenarios. Not sure how viable it would be overall but those interested could do a bit of experimenting.

**Comment by ameyer-pivotal** [comment] 2020-07-20 15:40
I understand the reasoning about why a buildpack can't easily do it, and why it would have to be performed by a platform (`pack` in this case). That said, I still think that this goes against the idea of CNBs so much that a buildpack approach ought to be investigated before adding a feature to `pack`.

**Comment by josegonzalez** [comment] 2020-07-20 21:52
I feel as though if you invoke `pack`, you should expect a buildpack to be run. If this was `docker build` and _that_ did auto-detection, the story would be different.

My personal opinion is that the proper way to do this would be for a platform to invoke either `pack build`, `docker build`, or whatever else, rather than have `pack` make a decision to not use buildpacks. Heroku does this, correct? Dokku does as well - we detect whether to use buildpacks or Dockerfile based on a few things (env vars, .env file, Dockerfile-existence...) and then do what makes sense for the platform.

**Comment by dfreilich** [comment] 2020-08-10 20:53
It seems like the consensus of a number of people above was to not pursue this, and allow implementors to create a buildpack which could run that. I'll close it, but feel free to reopen it if you feel it needs further discussion.

**Closed by dfreilich** 2020-08-10 20:53 UTC
Labels: status/discussion-needed, type/enhancement
