### ISSUE TITLE
Tests failed: TestTrustedBuilderCommand and other 6 tests

### ISSUE THREAD

**Issue by timmyyuan** [buildpacks/pack#1168] opened 2021-05-10 08:31 UTC
### Summary

There are 7 tests failed when running `make test`:
```
TestTrustedBuilderCommand
TestConfigDefaultBuilder
TestConfigPullPolicy
TestConfigRegistriesDefault
TestConfigRegistries
TestConfigRunImageMirrors
TestConfigLifecyleImage
```

---

##### Steps

1. checkout v0.18.1
2. make test

##### Current behavior

```
2021-05-10T03:47:58.6128452Z === RUN   TestTrustedBuilderCommand
2021-05-10T03:47:58.6129741Z Suite: TrustedBuilderCommands
2021-05-10T03:47:58.6130833Z Total: 13 | Focused: 0 | Pending: 0
2021-05-10T03:47:58.6131676Z Random seed: 1620618343
2021-05-10T03:47:58.6133034Z === RUN   TestTrustedBuilderCommand/TrustedBuilderCommands
2021-05-10T03:47:58.6135577Z === RUN   TestTrustedBuilderCommand/TrustedBuilderCommands/add/builder_is_provided/builder_is_a_suggested_builder/does_nothing
2021-05-10T03:47:58.6139165Z === RUN   TestTrustedBuilderCommand/TrustedBuilderCommands/add/builder_is_provided/builder_is_already_trusted/does_nothing
2021-05-10T03:47:58.6142493Z === RUN   TestTrustedBuilderCommand/TrustedBuilderCommands/add/builder_is_provided/builder_is_not_already_trusted/updates_the_config
2021-05-10T03:47:58.6146404Z === RUN   TestTrustedBuilderCommand/TrustedBuilderCommands/add/can't_write_to_config_path/fails
2021-05-10T03:47:58.6148754Z     config_trusted_builder_test.go:139: Expected an error but got nil
2021-05-10T03:47:58.6150833Z === RUN   TestTrustedBuilderCommand/TrustedBuilderCommands/add/no_builder_is_provided/prints_usage
2021-05-10T03:47:58.6152542Z Error: accepts 1 arg(s), received 0
2021-05-10T03:47:58.6153153Z 
2021-05-10T03:47:58.6155055Z === RUN   TestTrustedBuilderCommand/TrustedBuilderCommands/list/shows_suggested_builders_and_locally_trusted_builder_in_alphabetical_order
2021-05-10T03:47:58.6157565Z === RUN   TestTrustedBuilderCommand/TrustedBuilderCommands/no_args/prints_list_of_trusted_builders
2021-05-10T03:47:58.6161188Z === RUN   TestTrustedBuilderCommand/TrustedBuilderCommands/no_args/works_with_alias_of_trusted-builders
2021-05-10T03:47:58.6163799Z === RUN   TestTrustedBuilderCommand/TrustedBuilderCommands/remove/builder_wasn't_already_trusted/does_nothing_and_reports_builder_wasn't_trusted
2021-05-10T03:47:58.6166129Z === RUN   TestTrustedBuilderCommand/TrustedBuilderCommands/remove/builder_is_already_trusted/removes_builder_from_the_config
2021-05-10T03:47:58.6169007Z === RUN   TestTrustedBuilderCommand/TrustedBuilderCommands/remove/builder_is_already_trusted/removes_only_the_named_builder_when_multiple_builders_are_trusted
2021-05-10T03:47:58.6171733Z === RUN   TestTrustedBuilderCommand/TrustedBuilderCommands/remove/no_builder_is_provided/prints_usage
2021-05-10T03:47:58.6172816Z Error: accepts 1 arg(s), received 0
2021-05-10T03:47:58.6174321Z === RUN   TestTrustedBuilderCommand/TrustedBuilderCommands/remove/builder_is_a_suggested_builder/does_nothing_and_reports_that_
2021-05-10T03:47:58.6175378Z 
2021-05-10T03:47:58.6176144Z Passed: 12 | Failed: 1 | Skipped: 0

2021-05-10T03:47:58.5211900Z === RUN   TestConfigDefaultBuilder
2021-05-10T03:47:58.5213586Z Suite: ConfigDefaultBuilderCommand
2021-05-10T03:47:58.5215003Z Total: 11 | Focused: 0 | Pending: 0
2021-05-10T03:47:58.5216118Z Random seed: 1620618343
2021-05-10T03:47:58.5218303Z === RUN   TestConfigDefaultBuilder/ConfigDefaultBuilderCommand
2021-05-10T03:47:58.5223065Z === RUN   TestConfigDefaultBuilder/ConfigDefaultBuilderCommand/#ConfigDefaultBuilder/set/non-existent_builder_is_provided/error_is_present
2021-05-10T03:47:58.5227457Z === RUN   TestConfigDefaultBuilder/ConfigDefaultBuilderCommand/#ConfigDefaultBuilder/set/invalid_builder_is_provided/error_is_presented
2021-05-10T03:47:58.5231702Z === RUN   TestConfigDefaultBuilder/ConfigDefaultBuilderCommand/#ConfigDefaultBuilder/set/valid_builder_is_provider/in_local/sets_default_builder
2021-05-10T03:47:58.5236166Z === RUN   TestConfigDefaultBuilder/ConfigDefaultBuilderCommand/#ConfigDefaultBuilder/set/valid_builder_is_provider/in_local/gives_clear_error_if_unable_to_write_to_config
2021-05-10T03:47:58.5239332Z     config_default_builder_test.go:134: Expected an error but got nil
2021-05-10T03:47:58.5240326Z 
2021-05-10T03:47:58.5242787Z === RUN   TestConfigDefaultBuilder/ConfigDefaultBuilderCommand/#ConfigDefaultBuilder/set/valid_builder_is_provider/in_remote/sets_default_builder
2021-05-10T03:47:58.5247433Z === RUN   TestConfigDefaultBuilder/ConfigDefaultBuilderCommand/#ConfigDefaultBuilder/set/valid_builder_is_provider/in_remote/gives_clear_error_if_unable_to_inspect_remote_image
2021-05-10T03:47:58.5251857Z === RUN   TestConfigDefaultBuilder/ConfigDefaultBuilderCommand/#ConfigDefaultBuilder/unset/gives_clear_error_if_unable_to_write_to_config
2021-05-10T03:47:58.5254727Z     config_default_builder_test.go:103: Expected an error but got nil
2021-05-10T03:47:58.5257996Z === RUN   TestConfigDefaultBuilder/ConfigDefaultBuilderCommand/#ConfigDefaultBuilder/unset/clarifies_if_no_builder_was_set
2021-05-10T03:47:58.5260127Z 
2021-05-10T03:47:58.5262519Z === RUN   TestConfigDefaultBuilder/ConfigDefaultBuilderCommand/#ConfigDefaultBuilder/unset/unsets_current_default_builder
2021-05-10T03:47:58.5266769Z === RUN   TestConfigDefaultBuilder/ConfigDefaultBuilderCommand/#ConfigDefaultBuilder/no_args/lists_current_default_builder_if_one_is_set
2021-05-10T03:47:58.5270941Z === RUN   TestConfigDefaultBuilder/ConfigDefaultBuilderCommand/#ConfigDefaultBuilder/no_args/suggests_setting_a_builder_if_none_is_set
2021-05-10T03:47:58.5273115Z 
2021-05-10T03:47:58.5273995Z Passed: 9 | Failed: 2 | Skipped: 0

2021-05-10T03:47:58.5517041Z === RUN   TestConfigPullPolicy
2021-05-10T03:47:58.5518499Z Suite: ConfigPullPolicyCommand
2021-05-10T03:47:58.5519819Z Total: 12 | Focused: 0 | Pending: 0
2021-05-10T03:47:58.5520807Z Random seed: 1620618343
2021-05-10T03:47:58.5522319Z === RUN   TestConfigPullPolicy/ConfigPullPolicyCommand
2021-05-10T03:47:58.5525208Z === RUN   TestConfigPullPolicy/ConfigPullPolicyCommand/#ConfigPullPolicy/unset/removes_set_policy_and_resets_to_default_pull_policy
2021-05-10T03:47:58.5528789Z === RUN   TestConfigPullPolicy/ConfigPullPolicyCommand/#ConfigPullPolicy/unset/returns_clear_error_if_fails_to_write
2021-05-10T03:47:58.5531373Z     config_pull_policy_test.go:181: Expected "writing config to" an error but got nil
2021-05-10T03:47:58.5534058Z === RUN   TestConfigPullPolicy/ConfigPullPolicyCommand/#ConfigPullPolicy/set/valid_policy_is_specified/sets_the_policy_in_config
2021-05-10T03:47:58.5538164Z === RUN   TestConfigPullPolicy/ConfigPullPolicyCommand/#ConfigPullPolicy/set/valid_policy_is_specified/returns_clear_error_if_fails_to_write
2021-05-10T03:47:58.5540172Z 
2021-05-10T03:47:58.5541464Z     config_pull_policy_test.go:161: Expected "writing config to" an error but got nil
2021-05-10T03:47:58.5544262Z === RUN   TestConfigPullPolicy/ConfigPullPolicyCommand/#ConfigPullPolicy/set/invalid_policy_is_specified/does_not_write_invalid_policy_to_config
2021-05-10T03:47:58.5546401Z 
2021-05-10T03:47:58.5548762Z === RUN   TestConfigPullPolicy/ConfigPullPolicyCommand/#ConfigPullPolicy/set/policy_provided_is_the_same_as_configured_pull_policy/provides_a_helpful_message
2021-05-10T03:47:58.5552898Z === RUN   TestConfigPullPolicy/ConfigPullPolicyCommand/#ConfigPullPolicy/set/policy_provided_is_the_same_as_configured_pull_policy/it_does_not_change_the_configured_policy
2021-05-10T03:47:58.5556913Z === RUN   TestConfigPullPolicy/ConfigPullPolicyCommand/#ConfigPullPolicy/list/policy_set_to_never_in_config/lists_never_as_pull_policy
2021-05-10T03:47:58.5560463Z === RUN   TestConfigPullPolicy/ConfigPullPolicyCommand/#ConfigPullPolicy/list/policy_set_to_always_in_config/lists_always_as_pull_policy
2021-05-10T03:47:58.5564026Z === RUN   TestConfigPullPolicy/ConfigPullPolicyCommand/#ConfigPullPolicy/list/no_policy_is_specified/lists_default_pull_policy
2021-05-10T03:47:58.5569102Z === RUN   TestConfigPullPolicy/ConfigPullPolicyCommand/#ConfigPullPolicy/list/policy_set_to_if-not-present_in_config/lists_if-not-present_as_pull_policy
2021-05-10T03:47:58.5573339Z === RUN   TestConfigPullPolicy/ConfigPullPolicyCommand/#ConfigPullPolicy/--unset_and_policy_to_set_is_provided/errors
2021-05-10T03:47:58.5575158Z 
2021-05-10T03:47:58.5576179Z Passed: 10 | Failed: 2 | Skipped: 0

2021-05-10T03:47:58.5632142Z === RUN   TestConfigRegistriesDefault
2021-05-10T03:47:58.5633373Z Suite: ConfigRegistriesDefaultCommand
2021-05-10T03:47:58.5634150Z Total: 9 | Focused: 0 | Pending: 0
2021-05-10T03:47:58.5635431Z === RUN   TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand
2021-05-10T03:47:58.5638290Z === RUN   TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/list/returns_official_if_none_is_set
2021-05-10T03:47:58.5641513Z === PAUSE TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/list/returns_official_if_none_is_set
2021-05-10T03:47:58.5645062Z === RUN   TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/list/returns_the_default_registry_if_one_is_set
2021-05-10T03:47:58.5648905Z === PAUSE TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/list/returns_the_default_registry_if_one_is_set
2021-05-10T03:47:58.5653034Z === RUN   TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/set_default/should_set_the_default_registry
2021-05-10T03:47:58.5656812Z === PAUSE TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/set_default/should_set_the_default_registry
2021-05-10T03:47:58.5661035Z === RUN   TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/set_default/should_fail_if_no_corresponding_registry_exists
2021-05-10T03:47:58.5664711Z === PAUSE TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/set_default/should_fail_if_no_corresponding_registry_exists
2021-05-10T03:47:58.5668223Z === RUN   TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/set_default/returns_clear_error_if_fails_to_write
2021-05-10T03:47:58.5671683Z === PAUSE TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/set_default/returns_clear_error_if_fails_to_write
2021-05-10T03:47:58.5677255Z === RUN   TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/--unset/should_unset_the_default_registry,_if_set
2021-05-10T03:47:58.5685080Z === PAUSE TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/--unset/should_unset_the_default_registry,_if_set
2021-05-10T03:47:58.5690067Z === RUN   TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/--unset/should_return_an_error_if_official_registry_is_being_unset
2021-05-10T03:47:58.5694052Z === PAUSE TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/--unset/should_return_an_error_if_official_registry_is_being_unset
2021-05-10T03:47:58.5698276Z === RUN   TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/--unset/should_return_a_clear_message_if_no_registry_is_set
2021-05-10T03:47:58.5702597Z === PAUSE TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/--unset/should_return_a_clear_message_if_no_registry_is_set
2021-05-10T03:47:58.5707312Z === RUN   TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/--unset/returns_clear_error_if_fails_to_write
2021-05-10T03:47:58.5711818Z === PAUSE TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/--unset/returns_clear_error_if_fails_to_write
2021-05-10T03:47:58.5716295Z === CONT  TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/list/returns_official_if_none_is_set
2021-05-10T03:47:58.5720900Z === CONT  TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/--unset/returns_clear_error_if_fails_to_write
2021-05-10T03:47:58.5723741Z     config_registries_default_test.go:144: Expected "writing config to" an error but got nil
2021-05-10T03:47:58.5724818Z 
2021-05-10T03:47:58.5727968Z === CONT  TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/--unset/should_return_a_clear_message_if_no_registry_is_set
2021-05-10T03:47:58.5732436Z === CONT  TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/--unset/should_return_an_error_if_official_registry_is_being_unset
2021-05-10T03:47:58.5737229Z === CONT  TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/--unset/should_unset_the_default_registry,_if_set
2021-05-10T03:47:58.5741663Z === CONT  TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/set_default/returns_clear_error_if_fails_to_write
2021-05-10T03:47:58.5744370Z     config_registries_default_test.go:112: Expected "writing config to" an error but got nil
2021-05-10T03:47:58.5747838Z === CONT  TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/set_default/should_fail_if_no_corresponding_registry_exists
2021-05-10T03:47:58.5751969Z === CONT  TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/list/returns_the_default_registry_if_one_is_set
2021-05-10T03:47:58.5754241Z 
2021-05-10T03:47:58.5756952Z === CONT  TestConfigRegistriesDefault/ConfigRegistriesDefaultCommand/#ConfigRegistriesDefault/set_default/should_set_the_default_registry
2021-05-10T03:47:58.5759239Z 
2021-05-10T03:47:58.5760096Z Passed: 7 | Failed: 2 | Skipped: 0

2021-05-10T03:47:58.5809188Z === RUN   TestConfigRegistries
2021-05-10T03:47:58.5810333Z Suite: ConfigRegistriesCommand
2021-05-10T03:47:58.5811358Z Total: 18 | Focused: 0 | Pending: 0
2021-05-10T03:47:58.5812143Z Random seed: 1620618343
2021-05-10T03:47:58.5813709Z === RUN   TestConfigRegistries/ConfigRegistriesCommand
2021-05-10T03:47:58.5815958Z === RUN   TestConfigRegistries/ConfigRegistriesCommand/no_args/calls_list
2021-05-10T03:47:58.5819575Z === RUN   TestConfigRegistries/ConfigRegistriesCommand/-h/prints_help_text
2021-05-10T03:47:58.5821497Z === RUN   TestConfigRegistries/ConfigRegistriesCommand/list/should_indicate_official_as_the_default_registry_by_default
2021-05-10T03:47:58.5823777Z === RUN   TestConfigRegistries/ConfigRegistriesCommand/list/should_list_registries_in_verbose_mode
2021-05-10T03:47:58.5826245Z === RUN   TestConfigRegistries/ConfigRegistriesCommand/list/should_list_all_registries
2021-05-10T03:47:58.5828115Z === RUN   TestConfigRegistries/ConfigRegistriesCommand/list/should_use_official_when_no_registries_are_defined
2021-05-10T03:47:58.5830883Z === RUN   TestConfigRegistries/ConfigRegistriesCommand/add/validation/should_validate_type
2021-05-10T03:47:58.5832596Z === RUN   TestConfigRegistries/ConfigRegistriesCommand/add/validation/fails_with_missing_args
2021-05-10T03:47:58.5834437Z Error: accepts 2 arg(s), received 0
2021-05-10T03:47:58.5836288Z === RUN   TestConfigRegistries/ConfigRegistriesCommand/add/validation/should_throw_error_when_registry_already_exists
2021-05-10T03:47:58.5839368Z === RUN   TestConfigRegistries/ConfigRegistriesCommand/add/validation/should_throw_error_when_registry_name_is_official
2021-05-10T03:47:58.5842178Z === RUN   TestConfigRegistries/ConfigRegistriesCommand/add/validation/returns_clear_error_if_fails_to_write
2021-05-10T03:47:58.5844454Z     config_registries_test.go:259: Expected "writing config to" an error but got nil
2021-05-10T03:47:58.5847026Z === RUN   TestConfigRegistries/ConfigRegistriesCommand/add/default_is_true/sets_newly_added_registry_as_the_default
2021-05-10T03:47:58.5848652Z 
2021-05-10T03:47:58.5850155Z === RUN   TestConfigRegistries/ConfigRegistriesCommand/add/add_buildpack_registry/adds_to_registry_list
2021-05-10T03:47:58.5852712Z === RUN   TestConfigRegistries/ConfigRegistriesCommand/remove/should_remove_the_registry_and_matching_default_registry_name
2021-05-10T03:47:58.5855974Z === RUN   TestConfigRegistries/ConfigRegistriesCommand/remove/should_remove_the_registry
2021-05-10T03:47:58.5858799Z === RUN   TestConfigRegistries/ConfigRegistriesCommand/remove/should_return_error_when_registry_does_NOT_already_exist
2021-05-10T03:47:58.5861078Z === RUN   TestConfigRegistries/ConfigRegistriesCommand/remove/should_throw_error_when_registry_name_is_official
2021-05-10T03:47:58.5862887Z === RUN   TestConfigRegistries/ConfigRegistriesCommand/remove/returns_clear_error_if_fails_to_write
2021-05-10T03:47:58.5864966Z     config_registries_test.go:336: Expected "writing config to" an error but got nil
2021-05-10T03:47:58.5866651Z 
2021-05-10T03:47:58.5866892Z 
2021-05-10T03:47:58.5867343Z Passed: 16 | Failed: 2 | Skipped: 0

2021-05-10T03:47:58.5931233Z === RUN   TestConfigRunImageMirrors
2021-05-10T03:47:58.5933087Z Suite: ConfigRunImageMirrorsCommand
2021-05-10T03:47:58.5934432Z Total: 17 | Focused: 0 | Pending: 0
2021-05-10T03:47:58.5935539Z Random seed: 1620618343
2021-05-10T03:47:58.5937163Z === RUN   TestConfigRunImageMirrors/ConfigRunImageMirrorsCommand
2021-05-10T03:47:58.5940249Z === RUN   TestConfigRunImageMirrors/ConfigRunImageMirrorsCommand/no_arguments/lists_run_image_mirrors
2021-05-10T03:47:58.5944300Z === RUN   TestConfigRunImageMirrors/ConfigRunImageMirrorsCommand/-h/prints_available_commands
2021-05-10T03:47:58.5948085Z === RUN   TestConfigRunImageMirrors/ConfigRunImageMirrorsCommand/add/mirrors_are_provided/adds_them_as_mirrors_to_the_config
2021-05-10T03:47:58.5952105Z === RUN   TestConfigRunImageMirrors/ConfigRunImageMirrorsCommand/add/config_path_doesn't_exist/fails_to_run
2021-05-10T03:47:58.5954707Z     config_run_image_mirrors_test.go:113: Expected an error but got nil
2021-05-10T03:47:58.5957605Z === RUN   TestConfigRunImageMirrors/ConfigRunImageMirrorsCommand/add/no_run_image_is_specified/fails_to_run
2021-05-10T03:47:58.5960428Z 
2021-05-10T03:47:58.5961366Z Error: accepts 1 arg(s), received 0
2021-05-10T03:47:58.5963484Z === RUN   TestConfigRunImageMirrors/ConfigRunImageMirrorsCommand/add/no_mirrors_are_provided/preserves_old_mirrors,_and_prints_helpful_message
2021-05-10T03:47:58.5968327Z === RUN   TestConfigRunImageMirrors/ConfigRunImageMirrorsCommand/remove/run_image_provided_isn't_present/prints_a_clear_message
2021-05-10T03:47:58.5971787Z === RUN   TestConfigRunImageMirrors/ConfigRunImageMirrorsCommand/remove/no_run_image_is_specified/fails_to_run
2021-05-10T03:47:58.5973978Z Error: accepts 1 arg(s), received 0
2021-05-10T03:47:58.5977333Z === RUN   TestConfigRunImageMirrors/ConfigRunImageMirrorsCommand/remove/config_path_doesn't_exist/fails_to_run
2021-05-10T03:47:58.5981263Z     config_run_image_mirrors_test.go:165: Expected an error but got nil
2021-05-10T03:47:58.5984182Z === RUN   TestConfigRunImageMirrors/ConfigRunImageMirrorsCommand/remove/mirrors_are_provided/removes_them_for_the_given_run_image
2021-05-10T03:47:58.5986467Z 
2021-05-10T03:47:58.5988901Z === RUN   TestConfigRunImageMirrors/ConfigRunImageMirrorsCommand/remove/mirrors_are_provided/removes_the_image_if_all_mirrors_are_removed
2021-05-10T03:47:58.5993054Z === RUN   TestConfigRunImageMirrors/ConfigRunImageMirrorsCommand/remove/no_mirrors_are_provided/removes_all_mirrors_for_the_given_run_image
2021-05-10T03:47:58.5997217Z === RUN   TestConfigRunImageMirrors/ConfigRunImageMirrorsCommand/remove/no_mirrors_are_provided/preserves_all_mirrors_aside_from_the_given_run_image
2021-05-10T03:47:58.6001306Z === RUN   TestConfigRunImageMirrors/ConfigRunImageMirrorsCommand/list/run_image_provided/mirrors_are_set/returns_image_mirrors
2021-05-10T03:47:58.6006064Z === RUN   TestConfigRunImageMirrors/ConfigRunImageMirrorsCommand/list/run_image_provided/mirrors_aren't_set/prints_a_clear_message
2021-05-10T03:47:58.6009737Z === RUN   TestConfigRunImageMirrors/ConfigRunImageMirrorsCommand/list/no_run_image_mirrors_were_set/prints_a_clear_message
2021-05-10T03:47:58.6013141Z === RUN   TestConfigRunImageMirrors/ConfigRunImageMirrorsCommand/list/mirrors_were_previously_set/lists_run_image_mirrors
2021-05-10T03:47:58.6014969Z 
2021-05-10T03:47:58.6016121Z Passed: 15 | Failed: 2 | Skipped: 0

2021-05-10T03:47:58.5384941Z === RUN   TestConfigLifecyleImage
2021-05-10T03:47:58.5386448Z Suite: ConfigLifecycleImage
2021-05-10T03:47:58.5387540Z Total: 12 | Focused: 0 | Pending: 0
2021-05-10T03:47:58.5388447Z Random seed: 1620618343
2021-05-10T03:47:58.5389803Z === RUN   TestConfigLifecyleImage/ConfigLifecycleImage
2021-05-10T03:47:58.5392982Z === RUN   TestConfigLifecyleImage/ConfigLifecycleImage/#ConfigLifecycleImage/unset/the_custom_lifecycle_image_is_set/removes_set_lifecycle_image_and_resets_to_default_lifecycle_image
2021-05-10T03:47:58.5397475Z === RUN   TestConfigLifecyleImage/ConfigLifecycleImage/#ConfigLifecycleImage/unset/the_custom_lifecycle_image_is_set/returns_clear_error_if_fails_to_write
2021-05-10T03:47:58.5401529Z     config_lifecycle_image_test.go:162: Expected "failed to write to config at" an error but got nil
2021-05-10T03:47:58.5404802Z === RUN   TestConfigLifecyleImage/ConfigLifecycleImage/#ConfigLifecycleImage/unset/the_custom_lifecycle_image_is_not_set/returns_clear_message_that_no_custom_lifecycle_image_is_set
2021-05-10T03:47:58.5407278Z 
2021-05-10T03:47:58.5410665Z === RUN   TestConfigLifecyleImage/ConfigLifecycleImage/#ConfigLifecycleImage/set/invalid_lifecycle-image_is_specified/returns_an_error
2021-05-10T03:47:58.5415337Z === RUN   TestConfigLifecyleImage/ConfigLifecycleImage/#ConfigLifecycleImage/set/invalid_lifecycle-image_is_specified/returns_clear_error_if_fails_to_write
2021-05-10T03:47:58.5418997Z     config_lifecycle_image_test.go:135: Expected "failed to write to config at" an error but got nil
2021-05-10T03:47:58.5420625Z 
2021-05-10T03:47:58.5423866Z === RUN   TestConfigLifecyleImage/ConfigLifecycleImage/#ConfigLifecycleImage/set/valid_lifecycle-image_is_specified/sets_the_lifecycle-image_in_config
2021-05-10T03:47:58.5428658Z === RUN   TestConfigLifecyleImage/ConfigLifecycleImage/#ConfigLifecycleImage/set/valid_lifecycle-image_is_specified/returns_clear_error_if_fails_to_write
2021-05-10T03:47:58.5430844Z     config_lifecycle_image_test.go:122: Expected "failed to write to config at" an error but got nil
2021-05-10T03:47:58.5431539Z 
2021-05-10T03:47:58.5433459Z === RUN   TestConfigLifecyleImage/ConfigLifecycleImage/#ConfigLifecycleImage/set/custom_lifecycle-image_provided_is_the_same_as_configured_lifecycle-image/provides_a_helpful_message
2021-05-10T03:47:58.5436602Z === RUN   TestConfigLifecyleImage/ConfigLifecycleImage/#ConfigLifecycleImage/set/custom_lifecycle-image_provided_is_the_same_as_configured_lifecycle-image/it_does_not_change_the_configured
2021-05-10T03:47:58.5440463Z === RUN   TestConfigLifecyleImage/ConfigLifecycleImage/#ConfigLifecycleImage/list/no_custom_lifecycle_image_was_set/lists_the_default
2021-05-10T03:47:58.5444431Z === RUN   TestConfigLifecyleImage/ConfigLifecycleImage/#ConfigLifecycleImage/list/custom_lifecycle-image_was_set/lists_the_custom_image
2021-05-10T03:47:58.5448547Z === RUN   TestConfigLifecyleImage/ConfigLifecycleImage/#ConfigLifecycleImage/--unset_and_lifecycle_image_to_set_is_provided/errors
2021-05-10T03:47:58.5450325Z 
2021-05-10T03:47:58.5451172Z Passed: 9 | Failed: 3 | Skipped: 0
```

##### Expected behavior

These tests passed
---

### Environment

```
$ uname -a
Linux vultr.guest 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

##### pack info

v0.18.1

##### docker info

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version: 62250c13fe171a330340d8d95a9c6ef2b4a240a5
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-65-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.775GiB
 Name: vultr.guest
 ID: 6NXC:HFGE:QTQQ:KGAS:VPGB:AZ65:K52T:3KF5:2M2O:G2LH:D3QF:E7MD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by jromero** [comment] 2021-05-11 15:11
This is a very interesting set of errors. It appears as if our tests intended to make it so that certain files aren't writable are able to write in your environment. Could you provide the output of `umask`?

For example:

```
❯ umask
0022
```

**Comment by timmyyuan** [comment] 2021-05-12 06:42
Of course, the output is 
```
$ umask
0022
```

**Comment by natalieparellano** [comment] 2023-08-21 16:28
@timmyyuan are you still seeing this issue?

**Comment by natalieparellano** [comment] 2023-08-22 20:06
Closing as we haven't been able to reproduce this and the code base has drifted quite a bit since the original issue was reported. If anyone encounters this again, please reopen!

**Closed by natalieparellano** 2023-08-22 20:06 UTC
Labels: type/bug, status/incomplete
