### ISSUE TITLE
pack inspect-builder prints garbled pack version

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/pack#590] opened 2020-04-21 19:32 UTC
### Summary
Pack version in `pack inspect-builder` doesn't display correctly

---

### Reproduction
```
$ pack inspect-builder cloudfoundry/cnb:bionic
Inspecting builder: cloudfoundry/cnb:bionic

REMOTE:

Description: Ubuntu bionic base image with buildpacks for Java, NodeJS and Golang

Created By:
  Name: Pack CLI
  Version: 0.10.0&#43;git-06d9983.build-259
```

##### Current behavior
Pack version is shown as `0.10.0&#43;git-06d9983.build-259`

##### Expected behavior
Pack version should match `0.10.0+git-06d9983.build-259`, the value in the `io.buildpacks.builder.metadata` label

```
$ docker inspect cloudfoundry/cnb:bionic | jq -r '.[].Config.Labels["io.buildpacks.builder.metadata"]' | jq .createdBy
{
  "name": "Pack CLI",
  "version": "0.10.0+git-06d9983.build-259"
}
```

---

##### pack info
```
$ pack report
Pack:
  Version:  0.10.0+git-06d9983.build-259
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.7.2
```

**Comment by zmackie** [comment] 2020-04-21 20:03
This is a duplicate of https://github.com/buildpacks/pack/issues/579 which has been addressed already.

**Closed by zmackie** 2020-04-21 20:03 UTC
Labels: status/triage, type/bug
