### ISSUE TITLE
Support multi arch build using buildx

### ISSUE THREAD

**Issue by rverma-dev** [buildpacks/pack#1171] opened 2021-05-11 08:39 UTC
### Description
With aws graviton and many other arm systems on the rise, it is good to have multi arch images.

### Proposed solution
Have a way to leverage buildx to build the multiarch images for defined platforms. Document an example for the same.

**Comment by jromero** [comment] 2021-05-11 19:53
Given that this is associated with ARM could you provide the specific configuration you're wishing to be possible?

Here's a "matrix" of all the components and how they interact. It would be nice to know which configuration is so that we may prioritize it appropriately.

Could your request be more-or-less formulated in the same way as... ?

> The user wants to build an **ARM image** using **amd64 buildpacks** on a **docker host running on amd64** from their workstation running on **amd64**.

**Comment by natalieparellano** [comment] 2021-06-01 15:23
@jromero did you mean to link [this document](https://docs.google.com/document/d/1j2EISF1OMIrqJiM826Bm-PYJ9ycCGwdfEKHzet3xIjA/edit)? FYI for those interested, there is an #arm channel in [CNB Slack](https://slack.buildpacks.io/) where some discussion is taking place.

**Comment by dm3ch** [comment] 2022-10-18 20:22
I have similar use-case. I believe author of this issue meant use case like docker buildx allows to achieve using `--platform linux/amd64,linux/arm64`. It could be described using the sentence from document (mentioned in https://github.com/buildpacks/pack/issues/1171#issuecomment-852214781) the following way:
- The user wants to build a multi-arch docker image containing ARM and x86_64 images using amd64 buildpacks on a docker host running on amd64 from their workstation running on amd64.
- The user wants to build a multi-arch docker image containing ARM and x86_64 images using arm64 buildpacks on a docker host running on arm64 from their workstation running on arm64.

**Comment by natalieparellano** [comment] 2023-08-18 19:43
Duplicate of https://github.com/buildpacks/pack/issues/1570

**Closed by natalieparellano** 2023-08-18 19:43 UTC
Labels: type/enhancement, status/incomplete
